# Generated by Django 4.2.2 on 2023-07-03 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='white', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='company_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='cars_app.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_capacity',
            field=models.FloatField(default=120.9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='is_new',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='model_name',
            field=models.CharField(default='dfg', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='number_of_past_owners',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='number_of_seats',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.FloatField(default=44),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='year_of_manufacture',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='founder',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='year_of_establishment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
