# Generated by Django 4.2.2 on 2023-07-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0002_car_color_car_company_id_car_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='is_new',
        ),
        migrations.AddField(
            model_name='car',
            name='car_condition',
            field=models.CharField(default='f', max_length=256),
            preserve_default=False,
        ),
    ]
