# Generated by Django 4.2.2 on 2023-07-13 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars_app', '0003_remove_car_is_new_car_car_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='address',
            field=models.CharField(default='sdvfgh', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(default='grdhtgfhjtrf', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
