# Generated by Django 4.2.2 on 2023-08-01 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars_app', '0004_car_user_owner_address_owner_phone_number_owner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='pic_url',
            field=models.URLField(db_column='pic_url', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_condition',
            field=models.CharField(choices=[('new', 'new'), ('used', 'used')], max_length=256),
        ),
        migrations.AlterField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
