# Generated by Django 4.2.2 on 2023-08-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0007_savedcar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='pic_url',
        ),
        migrations.AddField(
            model_name='picture',
            name='original',
            field=models.URLField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='thumbnail',
            field=models.URLField(max_length=512, null=True),
        ),
    ]
