# Generated by Django 4.2.2 on 2023-08-27 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars_app', '0008_remove_picture_pic_url_picture_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cars', to=settings.AUTH_USER_MODEL),
        ),
    ]
