# Generated by Django 4.2.2 on 2023-08-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0009_alter_savedcar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='number_of_seats',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
