# Generated by Django 4.2.2 on 2023-09-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0010_alter_car_color_alter_car_number_of_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='img_url',
            field=models.URLField(max_length=512, null=True),
        ),
    ]
