# Generated by Django 4.2.2 on 2023-09-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0011_owner_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(default='e', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(default='df'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='number_of_seats',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='pic_url',
            field=models.URLField(db_column='pic_url', default='SDFGHJ', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='sdfgh', max_length=256),
            preserve_default=False,
        ),
    ]
