# Generated by Django 4.2.2 on 2023-09-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0012_alter_car_color_alter_car_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pic_url',
            field=models.URLField(db_column='pic_url', max_length=512, null=True),
        ),
    ]
